version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql57
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crudpoo
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345a
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php72
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    links:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    environment:
      PMA_HOST: db
      PMA_DATABASE: crudpoo
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
    links:
      - db

volumes:
  dbdata: